#!/usr/bin/env ruby

require "open3"

class ImportmapUpdater
  def run
    @default_branch = default_branch

    outdated = outdated_packages

    if outdated.empty?
      puts "All importmap packages are up to date."
      return
    end

    outdated.each do |pkg|
      update_package(pkg)
    end
  end

  private

  def branch_exists?(branch)
    # Remove command injection risk by not interpolating the branch name
    local, = Open3.capture2("git", "branch", "--list", branch)
    return true unless local.strip.empty?

    # Remove command injection risk by not interpolating the branch name
    remote, = Open3.capture2("git", "ls-remote", "--heads", "origin", branch)
    !remote.strip.empty?
  end

  def pr_exists?(branch)
    # Remove command injection risk by not interpolating the branch name
    stdout, = Open3.capture2("gh", "pr", "list", "--head", branch, "--json", "number")
    !stdout.include?("[]")
  end

  def outdated_packages
    stdout, status = Open3.capture2("bin/importmap outdated")

    parse_outdated_table(stdout)
  end

  def parse_outdated_table(output)
    rows = output.lines.select { |l| l.strip.start_with?("|") }

    rows.drop(2).map do |row|
      cols = row.split("|").map(&:strip)

      {
        name: cols[1],
        current: cols[2],
        latest: cols[3]
      }
    end
  end

  def update_package(pkg)
    branch = branch_name(pkg)

    if branch_exists?(branch) || pr_exists?(branch)
      puts "Branch already exists for #{pkg[:name]} (#{branch}), skipping."
      return
    end

    puts "\nUpdating #{pkg[:name]} #{pkg[:current]} → #{pkg[:latest]}"

    run!("git checkout #{@default_branch}")
    run!("git pull origin #{@default_branch}")

    run!("git checkout -b #{branch}")

    run!("bin/importmap pin #{pkg[:name]}@#{pkg[:latest]}")

    if clean_worktree?
      puts "No changes detected after pin."
      run!("git checkout #{@default_branch}")
      run!("git branch -D #{branch}")
      return
    end

    run!("git add config/importmap.rb vendor/javascript")
    run!("git commit -m \"Bump #{pkg[:name]} from #{pkg[:current]} to #{pkg[:latest]}\"")

    run!("git push origin #{branch}")

    create_pr(pkg, branch)

    run!("git checkout #{@default_branch}")
  end

  def branch_name(pkg)
    "importmap-update-#{pkg[:name].gsub('/', '-')}-#{pkg[:latest]}"
  end

  def create_pr(pkg, branch)
    title = "Bump #{pkg[:name]} from #{pkg[:current]} to #{pkg[:latest]}"

    body = <<~BODY
      Automated importmap dependency update.

      Package: #{pkg[:name]}
      Current version: #{pkg[:current]}
      Latest version: #{pkg[:latest]}

      Generated by importmap updater.
    BODY

    run!("gh pr create --title \"#{title}\" --body \"#{body}\" --head #{branch}")
  end

  def default_branch
    stdout, status = Open3.capture2("git symbolic-ref refs/remotes/origin/HEAD")

    abort "Unable to determine default branch" unless status.success?

    stdout.strip.split("/").last
  end

  def clean_worktree?
    stdout, = Open3.capture2("git status --porcelain")
    stdout.strip.empty?
  end

  def run!(cmd)
    puts "→ #{cmd}"
    system(cmd) || abort("Command failed: #{cmd}")
  end
end

ImportmapUpdater.new.run
